FROM ubuntu:latest


# Install the packages needed to download and extract plink
RUN apt-get update && apt-get install -y \
    unzip\
    wget \
    texlive texlive-latex-extra fonts-ebgaramond texlive-xetex texlive-generic-extra texlive-latex-recommended  texlive-lang-arabic  culmus culmus-fancy
